gluetun-qbittorrent-port-manager:
  image: patrickaclark/gluetun-qbittorrent-port-manager:latest
  restart: unless-stopped
  network_mode: "service: gluetun"
  environment:
    QBITTORRENT_SERVER: localhost # IP Address of qbittorrent
    QBITTORRENT_PORT: 8080
    QBITTORRENT_USER: admin # username
    QBITTORRENT_PASS: adminadmin # password
    HTTP_S: http # Select 'http' or 'https' depending on if you use certificates.
    GLUETUN_HOST: localhost # IP or FQDN of gluetun control server
    GLUETUN_PORT: 8000 # port of gluetun control server
